import 'package:prac/models/Product.dart';

final List<Product> dummyShirts = [
  Product(
    id: 'shirt1',
    name: 'Classic cotton  Shirt',
    price: 1999,
    images: ['assets/images/munggyqamzvdgokxkupy.jpg'],
    description: 'classic cotton shirt for men with cool design and with cool texture',
    category: 'Shirt',
  ),
  Product(
    id: 'shirt2',
    name: 'white Shirt',
    price: 2499,
    description: 'white shirt for men with cool design and with cool texture',
    images: ['assets/images/shirt1.jpg'],
    category: 'Shirt',
  ),
  Product(
    id: 'shirt3',
    name: 'Black Formal Shirt',
    price: 2199,
    description: 'Black formal shirt for men with cool design ',
    images: ['assets/images/BlackWhiteBoldSimpleFashionProductPromotionLandscapeBanner_1920x850px_1900x1100px_400x533px_720x1080px_68.jpg'],
    category: 'Shirt',
  ),
  Product(
    id: 'shirt4',
    name: 'Printed Summer Shirt',
    price: 1799,
    description: 'green summer shirt cool design',
    images: ['assets/images/green.jpg'],
    category: 'Shirt',
  ),
  Product(
    id: 'shirt5',
    name: 'women T-Shirt ',
    price: 2099,
    description: 'Black t-shirt for women with cool design and with cool texture',
    images: ['assets/images/w1.jpg'],
    category: 'Shirt',
  ),
  Product(
    id: 'shirt6',
    name: 'Black men T-Shirt',
    price: 2099,
    description: 'casual shirt for men with cool design and with cool texture',
    images: ['assets/images/casual.jpg'],
    category: 'Shirt',
  ),
  Product(
    id: 'shirt7',
    name: 'Black Women T-Shirt',
    price: 2099,
    description: 'casual shirt for men with cool design and with cool texture',
    images: ['assets/images/casual.jpg'],
    category: 'Shirt',
  ),
  Product(
    id: 'shirt8',
    name: 'Black ,en T-Shirt',
    price: 2099,
    description: 'casual shirt for men with cool design and with cool texture',
    images: ['assets/images/green.jpg'],
    category: 'Shirt',
  ),
];

final List<Product> dummyJeans = [
  Product(
    id: 'jean1',
    name: 'Classic Blue Jeans',
    price: 2999,
    description: 'Classic blue jeans for everyday wear.',
    images: ['assets/images/JEANS 6.jpg'],
    category: 'Jean',
  ),
  Product(
    id: 'jean5',
    name: 'Distressed Jeans',
    price: 3199,
    description: 'Trendy distressed jeans with a modern look.',
    images: ['assets/images/JEANS 5.jpg'],
    category: 'Jean',
  ),
  Product(
    id: 'jean3',
    name: 'Washed Denim Jeans',
    price: 3299,
    description: 'Washed denim jeans for a stylish appearance.',
    images: ['assets/images/JEANS 4.jpg'],
    category: 'Jean',
  ),
  Product(
    id: 'jean2',
    name: 'Slim Fit Jeans',
    price: 3499,
    description: 'Slim fit jeans for a modern and comfortable fit.',
    images: ['assets/images/JEANS 3.jpg'],
    category: 'Jean',
  ),
  Product(
    id: 'jean4',
    name: 'Straight Cut Jeans',
    price: 2799,
    description: 'Straight cut jeans for a relaxed fit and classic look.',
    images: ['assets/images/JEANS 2.jpg'],
    category: 'Jean',
  ),
  Product(
    id: 'jean6',
    name: 'Black Denim Jeans',
    price: 3599,
    description: 'Black denim jeans that pair well with any outfit.',
    images: ['assets/images/JEANS 1.jpg'],
    category: 'Jean',
  ),
];

final List<Product> dummyShoes = [
  Product(
    id: 'shoe1',
    name: 'Classic White Sneakers',
    price: 2999,
    description: 'Classic white sneakers for men with a comfortable fit and stylish design.',
    images: ['assets/images/SHOES 6.jpg'],
    category: 'Shoes',
  ),
  Product(
    id: 'shoe2',
    name: 'Black Running Shoes',
    price: 3499,
    description: 'Black running shoes for daily workouts and casual wear.',
    images: ['assets/images/shoe2.jpg'],
    category: 'Shoes',
  ),
  Product(
    id: 'shoe3',
    name: 'Blue Sports Shoes',
    price: 2799,
    description: 'Blue sports shoes with breathable material and great grip.',
    images: ['assets/images/shoe3.jpg'],
    category: 'Shoes',
  ),
  Product(
    id: 'shoe4',
    name: 'Red Casual Shoes',
    price: 2599,
    description: 'Red casual shoes for a bold and trendy look.',
    images: ['assets/images/shoe4.jpg'],
    category: 'Shoes',
  ),
  Product(
    id: 'shoe5',
    name: 'Formal Black Shoes',
    price: 3999,
    description: 'Elegant formal black shoes perfect for office and events.',
    images: ['assets/images/shoe5.jpg'],
    category: 'Shoes',
  ),
  Product(
    id: 'shoe6',
    name: 'Brown Leather Boots',
    price: 4999,
    description: 'Brown leather boots for a rugged and stylish appearance.',
    images: ['assets/images/shoe6.jpg'],
    category: 'Shoes',
  ),
];

final List<Product> dummyJackets = [
  Product(
    id: 'jacket1',
    name: 'Black Leather Jacket',
    price: 5999,
    description: 'Classic black leather jacket for a timeless look.',
    images: ['assets/images/jacket1.jpg'],
    category: 'Jacket',
  ),
  Product(
    id: 'jacket2',
    name: ' Denim Jacket',
    price: 3999,
    description: ' denim jacket for casual outings.',
    images: ['assets/images/jacket2.jpg'],
    category: 'Jacket',
  ),
  Product(
    id: 'jacket3',
    name: ' Bomber Jacket',
    price: 4499,
    description: 'Trendy  bomber jacket for a modern style.',
    images: ['assets/images/jacket3.jpg'],
    category: 'Jacket',
  ),
  Product(
    id: 'jacket4',
    name: ' Winter Jacket',
    price: 6999,
    description: 'Warm  winter jacket for cold weather.',
    images: ['assets/images/jacket4.jpg'],
    category: 'Jacket',
  ),
  Product(
    id: 'jacket5',
    name: ' Puffer Jacket',
    price: 5499,
    description: ' puffer jacket for extra warmth and style.',
    images: ['assets/images/jacket5.jpg'],
    category: 'Jacket',
  ),
  Product(
    id: 'jacket6',
    name: ' Suede Jacket',
    price: 6499,
    description: ' suede jacket for a premium feel.',
    images: ['assets/images/jacket6.jpg'],
    category: 'Jacket',
  ),
  Product(
    id: 'jacket7',
    name: ' Windbreaker',
    price: 2999,
    description: 'Lightweight  windbreaker for outdoor activities.',
    images: ['assets/images/jacket7.jpg'],
    category: 'Jacket',
  ),
  Product(
    id: 'jacket7',
    name: 'Brown Suede Jacket',
    price: 6499,
    description: 'Brown suede jacket for a premium feel.',
    images: ['assets/images/jacket6.jpg'],
    category: 'Jacket',
  ),
]; 