/// Generated file. Do not edit.
/// This file is generated by the iFlutter
library;

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'prac';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String JACKET1 = 'assets/images/jacket1.jpg';
  static const String JACKET2 = 'assets/images/jacket2.jpg';
  static const String JACKET3 = 'assets/images/jacket3.jpg';
  static const String JACKET4 = 'assets/images/jacket4.jpg';
  static const String JACKET5 = 'assets/images/jacket5.jpg';
  static const String JACKET6 = 'assets/images/jacket6.jpg';
  static const String JACKET7 = 'assets/images/jacket7.jpg';
  static const String JEAN1 = 'assets/images/jean1.jpg';
  static const String JEAN2 = 'assets/images/jean2.jpg';
  static const String JEAN3 = 'assets/images/jean3.jpg';
  static const String JEAN4 = 'assets/images/jean4.jpg';
  static const String JEAN5 = 'assets/images/jean5.jpg';
  static const String JEAN6 = 'assets/images/jean6.jpg';
  static const String SHIRT6 = 'assets/images/shirt6.jpg';
  static const String SHOE1 = 'assets/images/shoe1.jpg';
  static const String SHOE2 = 'assets/images/shoe2.jpg';
  static const String SHOE3 = 'assets/images/shoe3.jpg';
  static const String SHOE4 = 'assets/images/shoe4.jpg';
  static const String SHOE5 = 'assets/images/shoe5.jpg';
  static const String SHOE6 = 'assets/images/shoe6.jpg';
}
